version: "1.0"
name: "ZenStack Workflow"
commands:
  - command: "bunx zenstack check"
    name: "Checking schema"
  
  - command: "bun zen:generate"
    name: "Generating Zenstack files"
  
  - command: "cp node_modules/.zenstack/.logical-prisma-client/index-fixed.d.ts prisma"
    name: "Copying Prisma types"
  
  - command: "rm -rf node_modules/.zenstack/zod"
    name: "Cleaning Zod files"
    skippable: true
  
  - command: "rm -f *.prisma"
    name: "Cleaning Prisma files"
    skippable: true
  
  - command: "rm -f prisma/schema.prisma"
    name: "Cleaning schema"
    skippable: true
  
  - command: "bun run prisma-field-omitter --config prisma/prisma-field-omitter.json"
    name: "Running field omitter"
